### ISSUE TITLE
Question on the the LSTM usage

### ISSUE THREAD

**Issue by evgliv** [knok/rcnn-text-classification#1]
Hi there,
Thank you for your research. It looks very promising. I'm trying to look at your code. And I have the question on the usage of variables _fwd_ and _bwd_ in model.py. They are used only in reset_state(). It's a little bit strange.  What did I miss? Thank you.

**Comment by knok** [comment]
It is unnecessary code, maybe.
I'll remove them later, thank you.

**Comment by knok** [comment]
fixed in ecd8bb93abb7ae74f0e2e8a5bc595314bdc35800.
