### ISSUE TITLE
Quesion on rcnn-text-classification

### ISSUE THREAD

**Issue by icerooqiu** [knok/rcnn-text-classification#2]
Hi there,

I have a question about the using, Is that your text-classification can only classify only 2 types?
For example,
"今日はなんだかい, い感じ",3
どうもやる気が出ない,0
明日もがんばろう,2
もう帰りたい,1
Does this work?

**Comment by knok** [comment]
You need to add classification categories number on LetterClassifyer.

in train.py:

```
-    m = LetterClassifyer(args.vocab, args.embed, args.hidden)
+    m = LetterClassifyer(args.vocab, args.embed, args.hidden, class=size=3)
```

**Comment by knok** [comment]
I added "--classes" option in train.py,  now you can work that.
